apiVersion: v1
kind: Service
metadata:
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: eck-elasticsearch
  name: eck-ingest-es-http-endpoint
  namespace: ${eck_namespace}
spec:
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: "eck-elasticsearch"
    acceptIngest: "true"
  sessionAffinity: None
  type: LoadBalancer
