apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: ${es_version}
  count: ${entsearch_pod_count}
  elasticsearchRef:
    name: eck-elasticsearch
  config:
    kibana.host: https://eck-kb-http.${eck_namespace}.svc:5601
  configRef:
    secretName: es-credentials
  podTemplate:
    metadata:
      labels:
        acceptIngest: "${entsearch_accept_ingest}"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - entsearch
      containers:
      - name: enterprise-search
        resources:
          requests:
            cpu: ${entsearch_pod_cpu}
            memory: ${entsearch_pod_memory}
        env:
        - name: JAVA_OPTS
          value: ${entsearch_pod_ES_JAVA_OPTS}