apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: ${eck_namespace}
spec:
  version: ${es_version}
  count: ${kibana_pod_count}
  elasticsearchRef:
    name: eck-elasticsearch
  enterpriseSearchRef:
    name: enterprise-search
  podTemplate:
    spec:
      nodeSelector:
        nodetype: ${kibana_pod_instance_affinity}
      containers:
      - name: kibana
        resources:
          requests:
            memory: ${kibana_pod_memory}
            cpu: ${kibana_pod_cpu}
  http:
   service:
    metadata:
         annotations:
    spec:
         type: LoadBalancer
   tls:
    selfSignedCertificate:
     subjectAltNames:
     - dns: "*.amazonaws.com"
